/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ChatBubble: typeof import('./src/components/chatBubble.vue')['default']
    ChatBubblebot: typeof import('./src/components/chatBubblebot.vue')['default']
    ChatBubbleusr: typeof import('./src/components/chatBubbleusr.vue')['default']
    ChatField: typeof import('./src/components/chatField.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
